logger:
  level: DEBUG

# global:

# dataset:

webquestions:
  train_train: "../data/input/webquestions.examples.train.train.json"
  train_validation: "../data/input/webquestions.examples.train.validation.json"
  train_tagged: "../data/generated/webquestions.examples.train.utterances.tagged.json"
  train_silvergraphs: "../data/generated/webquestions.examples.train.silvergraphs.full_11_29.json"
  train_choicegraphs: "../data/generated/webquestions.examples.train.choice_graphs.json"

model:
  threshold: 2000
  models.save.path: "../trainedmodels/"
  max.sent.len: 70
  emb.dim: 50
  vocab.size: 0 #set automatically
  graph.choices: 10 #set automatically
  sem.layer.size: 300
  conv.size: 100
  conv.width: 3
  dropout.sibling: 0.1

wikidata: False


