logger:
  level: DEBUG

global:
  random.seed: 1

training:
  train.generator: False
  log.results: "../data/training.log"

generation:
  max.num.entities: 2
  questions: "../data/input/webquestions.examples.train.json"
  save.choice.to: "../data/generated/webquestions.examples.train.choice_graphs.extended.json"
  save.silver.to: "../data/generated/webquestions.examples.train.silvergraphs.200.2.json"
  take_first: 200
  include_url_entities: True

webquestions:
  f1.samples.threshold: 0.1
  each.separate: False
  max.silver.samples: 15
  max.negative.samples: 30
  target.dist: True
  replace.entities: False
  extensions: ['hopUp', 'temporal', 'multi_rel', 'qualifier_rel', 'v-structure']
  path.to.dataset:
    train_train: "../data/input/webquestions.examples.train.train.json"
    train_validation: "../data/input/webquestions.examples.train.validation.json"
    train_tagged: "../data/generated/webquestions.examples.train.utterances.tagged.json"
    train_silvergraphs: "../data/generated/webquestions.examples.train.silvergraphs.full_12_05.json"
    train_choicegraphs: "../data/generated/webquestions.examples.train.choice_graphs.extended.json"

model:
  class: BagOfWordsModel
  threshold: 500
  models.save.path: "../trainedmodels/"
  word.embeddings: "../resources/glove/glove50B.tsv"
  max.sent.len: 70
  max.graph.size: 3
  loss: kld
  edge.with.entity: False
  epochs: 40
  batch.size: 128
  emb.dim: 50
  emb.sum: True # Max if false
  emb.train: False
  emb.weight.init: uniform
  vocab.size: 0 #set automatically
  graph.choices: 10 #set automatically
  samples.per.epoch: 1000 #set automatically
  sem.layer.depth: 1
  sem.layer.size: 300
  graph.sum: max
  sibling.weight.init: glorot_uniform
  conv.size: 100
  conv.width: 3
  dropout.sibling: 0.1
  dropout.sibling.pooling: 0.1
  early.stopping: 5
  monitor: acc
  twin.similarity: cos
  sibling.activation: relu

wikidata:
    evaluate: True

